name: AWS Auth
description: Autenticação AWS via OIDC

inputs:
  aws-region:
    description: 'Região AWS'
    required: true
  role-to-assume:
    description: 'ARN da Role IAM para assumir'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configurar credenciais AWS via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
